/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VaAwnXY6OEC
 */
import Link from "next/link";
import { ModeToggle } from "./toogle/theme";
import { Card, CardContent } from "./ui/card";
import Countdown from "./ui/count-down";
import { CheckIcon, Construction } from "lucide-react";
import { socials } from "../../utils/objects/socials";
export function UnderConstruction() {
  return (
    <Card className="mx-auto w-fit  flex flex-col items-center justify-center border border-primary ">
      <CardContent>
        <div className="flex flex-col items-center justify-center    gap-2 text-center">
          <div className="w-full justify-end flex flex-row gap-2 items-center">
            Theme
            <ModeToggle />
          </div>
          <div className="space-y-2">
            <Construction className="mx-auto h-20 w-20 " />
            <h1 className="text-5xl lg:text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Under Construction
            </h1>
            <p className="mx-auto lg:max-w-[500px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              I am working on something awesome! Please Check back soon.
            </p>
          </div>
          <Countdown targetDate="2024-03-11T23:59:59" />
          <div className="max-w-[600px] w-full grid gap-2 justify-center">
            <div className="flex items-start gap-4">
              <CheckIcon className="h-4 w-4 flex-shrink-0 text-gray-500 dark:text-gray-400" />
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Website design and layout completed.
              </p>
            </div>
            <div className="flex items-start gap-4">
              <CheckIcon className="h-4 w-4 flex-shrink-0 text-gray-500 dark:text-gray-400" />
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Content and media integration in progress.
              </p>
            </div>
            <div className="flex items-start gap-4">
              <CheckIcon className="h-4 w-4 flex-shrink-0 text-gray-500 dark:text-gray-400" />
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Final testing and optimization coming up next.
              </p>
            </div>
          </div>
          <Card className="flex gap-6 mt-6">
            {socials.map((social, index) => (
              <Link
                key={index}
                className="text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50"
                href={social.href}
                target="_blank"
              >
                <social.icon className="h-8 w-8" />
              </Link>
            ))}
          </Card>
        </div>
      </CardContent>
    </Card>
  );
}
